language: python
python:
  - 2.7

install:
  # Install Python dependancies
  - pip install --use-mirrors nose coveralls

  # Install JS dependancies
  - npm install karma karma-jasmine karma-phantomjs-launcher karma-coverage coveralls

script:
  # Run Python tests then send output to coveralls
  - nosetests && coveralls

  # Run JS tests (using Jasmine + Karma)
  - ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS test/js/karma.conf.js
